### ISSUE TITLE
Interrupts 

### ISSUE THREAD

**Issue by rodiba72** [CrazyIvan359/mqttany#101]
I have installed mqttany on a raspberry pi 3. I am not able to make interrupts work. Can you share some documentation? Thanks

**Comment by CrazyIvan359** [comment]
I cannot help you with no information like this. The [Documentation](https://crazyivan359.github.io/mqttany/index.html) is linked in several places, if you have not already, please read it.

If you need general troubleshooting help or just want to ask a question, please use the new [Discussions](https://github.com/CrazyIvan359/mqttany/discussions) feature.

I see you have now posted a bit more information on the [openHAB forum](https://community.openhab.org/t/problems-with-gpio/111298/3), but this is still not enough for me to work with. 

Make sure you are running the latest version of MQTTany, version 0.13.0, as there were some bugs related to GPIO Interrupts that made it into the v0.12.x versions. They have all been fixed and interrupts are working now.

If you are still having problems after doing these things, please open a new topic in the Discussions tab here on GitHub.
